name: Docker Image CI ARM64 Stable

on:
  push:
    branches: 
      - "stable"
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ARM64
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: softethervpn/vpnserver-arm64
          tags: |
            # branch event
            type=ref,event=branch
            # tag event
            type=ref,event=tag
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          #context: "{{defaultContext}}:build" #might be used later if Dockerfile is somewhere else
          file: ./Dockerfile.stable
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
